
== How To Build Momentum

The previous chapters of this book have described all the elements that go into creating and running an open-source project.
In this chapter, we discuss some things you can do to increase your project's chances for success.
This builds on the material in the section <<building-community>> in Chapter 6, which covers the basic things to do.
The next chapter focuses on what not to do based on lessons learned from the failures and mistakes we've observed in various open-source projects.

The ideas in this chapter apply to any open-source project;
however, we want to emphasize that a company engaging in an open-source project has many additional resources that can be used to further the project in ways that are not available to individual volunteers.
In addition to developers, a company also employs technical writers, user-interface experts, graphic artists, website designers, technology evangelists, marketing people, project managers, and people with other skills, all of whom can help with different aspects of the project.
Once they understand the open-source process, these folks can make major contributions to help the project become a success. All the activities that your company does to support a proprietary product — marketing, advertising, support, and training — are also needed for an open-source project.

As you read over this chapter, remember what your business goals are and focus on how to achieve them.
Creating a successful open-source project is only part of your strategy.
As the project grows and develops, it will take on a life of its own. You need to balance the needs of the open-source community against your business goals.
For the most part, they should be aligned toward a common purpose, and developers from both inside and outside of your company will work together to achieve them.
Where they are orthogonal, you should let the community proceed on its own.
If they are opposed, you need to be very upfront about communicating your plans and reach some agreement that does not alienate or frustrate your community.

For example, one of the business goals of the NetBeans project was for Sun to sell proprietary modules that added functionality to the basic NetBeans IDE.
Developing similar modules as open source in NetBeans would undermine this goal because the functionality would then be available for free.
However, outside developers have every right to expect that any useful modules they create can become part of NetBeans.
So the decision was made that any module could be developed for NetBeans.
It also was decided that when a NetBeans module duplicated the functionality of one of Sun's proprietary modules the Sun version would be open sourced.
In this way, the functionality level of NetBeans would continually go up, which would be good for the health of the project.
Sun could make this decision because the Sun engineers were confident that they would always be able to develop new proprietary modules that Sun could sell, so they did not need to hold tightly to their existing ones.

=== Marketing Your Project

As with any product, marketing plays a key role in the success of your project.
For you to be successful, people need to hear about your project, understand what it does, and see how it can help them.
Getting the message out about your project is one job marketing can help with.

==== What Is Your Project's Story?

Before your project is ever announced to the world, you need to come up with a compelling story that describes what your project is aiming at — something to get people excited about it.
This is the message that will attract people to your project both as users and potential developers.
If the story is not appealing, then people will not be interested in participating and won't get involved.

For most open-source projects, this story is focused on the technology being developed.
For example, the Apache HTTP Server Project exists to build the best web server.
The following are statements of the story for Apache.

____
The Apache Project is a collaborative software development effort aimed at creating a robust, commercial-grade, featureful, and freely-available source code implementation of an HTTP (Web) server.footnote:[https://httpd.apache.org/ABOUT_APACHE.html]
____

____
The goal of this project is to provide a secure, efficient and extensible server which provides HTTP services in sync with the current HTTP standards.footnote:[https://httpd.apache.org]
____

Other projects have a more user-centered focus, as seen in the following comment about GNOME.

____
The GNOME project was born as an effort to create an entirely free desktop environment for free systems. From the start, the main objective of GNOME has been to provide a user friendly suite of applications and an easy-to-use desktop.footnote:[https://www.gnome.org/intro/findout.html]
____

You need to determine what sort of people you are hoping to attract to your project.
If you want to mainly target end-users, then you need to talk about what they can do with the software you are developing, which of their problems your software solves.
If you want to focus on developers who will contribute code to your project, then emphasizing the technological aspects may work, but remember that most people working on open-source projects do so because they need to use the resulting software — your developers will also be users.

Creating a good story is hard work.
The story needs to express the shared purpose behind your project.
It will attract people who share this vision and are willing to work to make it real.
Moreover, the story should infuse all aspects of the project so that it provides guidance whenever a strategic decision must be made.
In literary theory, such a story is called a _topos_ and can be defined as follows:

____
a conventionalized expression or passage in text which comes to be used as a resource for the composition of additional texts.foonote:[_The New Princeton Encyclopedia of Poetry and Poetics_, p. 1294.]
____

_Topos_ literally means "place" or "location" in Greek, and a topos is a place from which similar stories can be woven.
An example from literature is the story of the Garden of Eden.
Anyone in a Western Judeo-Christian culture when asked to tell a story about the Garden of Eden will probably come up with a story consistent with the vision of creation the Garden of Eden presents.
An example of a technology-related topos is Moore's Law, which is regularly used as the basis of stories about the future of computing.

For an example of the power of a good story, consider the one developed for the Jini project.
As described earlier, Jini technology is a thin layer built on top of Java that allows applications to be written as remote services that can be dynamically deployed and located over a network.
The obvious story is that Jini is another middleware framework for distributed applications.
But this story has a technology focus that would have severely limited the spread of the Jini message — indeed the term _middleware_ causes even developers to yawn.
Instead, the Jini marketing team built a story around what Jini technology would mean to users;
that story generated lots of excitement in developers, the press, and the marketplace.

The Jini topos speaks of a world of "intelligent services" that "simply connect" to form "spontaneous networks" and describes a set of home, office, and automobile scenarios derived from this topos.
The concepts "simply connect" and "spontaneous networks" address how people relate to the technology.
The Jini topos was highly effective and created a thriving community and associated technology — as hoped — along with thriving E-Speak, UPnP, and SOAP communities and associated technologies.

This type of story is especially important for any project with ubiquity as a goal.
For Jini, success did not rest in extensive development of the core Jini protocols but rather in nurturing communities to create a wide range of Jini-based services.
The story needed to inspire companies to want their products — be they printers, cameras, or whatever — to "simply connect" by using Jini technology.

Contrast this with the Apache topos (described earlier) which speaks of web servers and technology for making them effective.
Whereas Jini projects tend to fan out, creating new services for people to use, the Apache Software Foundation's projects tend to focus on adding web server functionality and adopting related technologies such as Java Server Pages, servlets, and XML.

Topoi and storytelling, however, might not go over well with your highly technical developers.
Although the developers at Sun in the Jini group were involved in the story-making, they quickly came to believe that the story was misguided, because it talked exclusively about a world of small devices when in fact Jini was also capable in middleware and other high-end applications, such as distributed and scientific computing.
They became upset that Sun was actually not working diligently in the device space and so to them the story was a lie.

The idea of a topos, however, is that a topos enables people to make their own stories about their own areas of interest.
In fact, most middleware application writers had little trouble understanding that "simply connect" and "spontaneous networks" were either literally or metaphorically true for them, although they worried that less sophisticated people might not be able to understand the connection.

If you decide to build a topos, make sure your developers understand what it's for and buy into the topos you create.

At its best, the topos as a story-making story attracts and provides room for experimentation and variation beyond what the initiators envisioned.

==== The Name Matters

What you call your open-source project is important.
You need to choose a name that will attract developers.
In effect, you are creating a brand identity just like any commercial product.
You want to create an identity that matches your target audience and that is consistent with your story.
Most important, you don't want a name that is too slick or connected with a commercial product.

This can be complicated if part of your business plan is to develop a commercial product based on the open-source version.
You need to recognize the different naming requirements for each version.

For example, when Sun was deciding how to name its various Java IDE products, it used the more formal "Forte for Java" name for the Sun-branded versions and the more developer-friendly "NetBeans" name for the open-source version.
Keeping the NetBeans name was important for historical reasons, but as a name it does not really describe the project — a Java IDE and more generally a portable tools platform — so another name might have been better.

==== Getting the Message Out

Once you have a good story about your project, you need to tell it to people.
This is a traditional role for marketing.
When you have a major piece of news, such as when you first announce your project, your company's marketing machine can see to it that the world hears about it.
For very important announcements, this can include major stories in the press.
For instance, the initial stories about Sun's Jini technology appeared in the _New York Times_, _Business Week_, and _Wired_.
When top Sun executives such as Scott McNealy and Bill Joy gave talks or met with the press, they made sure to talk about what was new with Jini, JXTA, NetBeans, OpenOffice, and the other open-source projects Sun was working on.
Major stories were also featured on Sun's website, along with links to stories elsewhere on the Web.

In addition to the big-splash type of announcement, you should also maintain ongoing low-key press coverage.
This is essential because there is often a long time between the initial announcement and the final release.
You don't want people to think that your project is dead, so be sure to publicize ongoing activities such as community meetings, working group meetings, and significant milestones.
These can be as short as a single sentence in a column of industry news in a magazine.
Such stories should also be featured on the home page of your project's website.
Note that some PR folks are interested only in handling major stories and will balk at the smaller scale needed for ongoing coverage.
If they won't do it, then you need to find someone else who will.

If your project involves infrastructure or something that can be used as part of another application or website, try to find ways to take advantage of the pride some people find in using open-source code or in the technology of your project.
Create a logo, a graphic, or a sound that can easily be cut and pasted onto the splash screen of other applications or onto the website of some proud user of your stuff.
The logo can link to your website, drawing traffic.

==== Going beyond Standard Marketing

The conventional marketing channels — major newspapers and magazines, trade press, and trade shows — are important, but an open-source project has other ways to reach potential users and developers, including newsgroups, mailing lists, webzines, and weblogs.
Use all of these channels to market your project. 
ou should encourage your developers and users to post to whatever online forums are appropriate.

It is important to use a different writing style for material sent over these alternative channels.
This is a matter of voice.
Richard Rhodes, author of _The Making of the Atomic Bomb_, wrote:

____
Every work of writing, no matter how modest, no matter how seemingly "objective," no matter how "true," is composed in one or more fictional voices. "Someone" "tells" every story, even the copy on the back of cereal boxes, even a legal contract, even a street sign. We may not pause to puzzle out who "someone" is--the author may not even have thought about her choice of voice in advance--but we register "someone" 's presence and assess his statements accordingly.footnote:[Richard Rhodes, _How to Write: Advice and Reflections_, p. 36.]
____

Almost every reader is aware of the voice behind any writing, and so if you want to build a community, you need to make that community feel like a group of people, people with distinct and human voices.
Company writing typically tries to appear as neutral as possible, as much like an encyclopedia as possible, so there is little possibility of a reader hearing a voice behind the writing, a voice expressing an opinion.
The company in many cases wants the reader to believe that what is written is objectively true.
Marketing writing often puts a cheerleading sort of voice behind the words.

Anything that has a slick marketing feel or inauthentic voice will be rejected and probably will give people a negative view of your project.
Avoid hype.
What does work is honest talk from developer to developer or user to user.
As such, it is the opposite of the typical anonymous marketing message broadcast to a target audience.
Instead, it is a message from a real person attempting to engage in an ongoing conversation with other individuals.
Each message helps establish the reputation of the writer.
Your employees need to become known and respected members of the community in order to best communicate about your project.
A big test of their honesty is their being able to admit errors or mistakes and to acknowledge the successes of other projects.

One last point is that it is very important to give credit to the folks who did the work.
If a number of outside developers contributed to your open-source project, be sure to acknowledge their efforts.
You may even want to feature their efforts because it shows that the project goes beyond your company.

=== Focus on Your Users and Contributors

One of the most crucial factors in your project's success is releasing a useful product — one that works and solves a real problem.
This is exactly the same problem faced by any company releasing a commercial software application.
Open source works best with at least several thousand users, so your product must first attract that many.
Then the open-source process will encourage those users to provide feedback that will make your project more in tune with the needs of potential users.
Remember that one of the main points of doing open source is continuous design, which requires that you pay attention to the continuous feedback you're getting from the community.

If you have such a large code base that you plan on releasing it in several installments in order to give you time to scrub it, then make sure that the first release can build a complete and useful product.
Try to release the parts that are most valuable to users and developers first. As you release subsequent pieces, additional news stories about your project will be generated.

==== Target Your Potential Audience

As with any product, you need to identify what sort of person will benefit from using your product.
You need to make sure your message reaches those people.
This is where you can make use of standard marketing and advertising.

You also should target other companies that will benefit either from using your product directly or using it to add value to their customers.
For example, any company doing Java development can use NetBeans to increase the productivity of its programmers.
Other companies create commercial products that run on top of NetBeans.
In both cases, companies have an incentive to assign their own developers to work on NetBeans to add features they need, and indeed a number of companies have already done so.
For any open-source project, companies provide a good source of potential developers.

==== Make Users Successful

Installing and learning to use a piece of new software is always a major hurdle for people.
As discussed in <<good-initial-experience>> in Chapter 6, it is important that you make things as easy as possible.
Every person who can't install your application or who is unable to get it to run will be sure to mention those problems to other potential users.
You want the message sent by word of mouth to be that people should try your product, not that it should be avoided.

Good documentation, tutorials, and training will also help your users to succeed.
The ideas behind open source encourage users to help each other, so provide ways for them to do so via your project's website:
Create user mailing lists and discussion forums.
Compile FAQs.
Do everything you can to encourage the formation of an active user community.
There may even be more than one, so you may need to foster several developing communities.
They might be separated by what they do with the product (for example, Java vs. C programmers) or by other factors (for example, French vs. German speakers).
For large projects, work with a publisher to get a book written about how to best use your software.

Most active communities have an email-based communications flavor to them.
One reason that urban settings seem energized is that there are constant noise and interruptions — actual evidence of energy.
A community that thrives on email is one that interrupts people with frequent email.
Some community members--often the most active ones--are eager for such interruptions.
A community with no such interruptions, with only a website (even with wikis and weblogs) will seem placid and low energy by comparison.
When people need to go see whether something is happening, they tend to go see a little less frequently as time goes on.
For energetic email-based communities, there needs to be a way for people to get respite and opt to come around to see what's happening or receive relatively infrequent email digests.

Do releases as frequently as makes sense.
Small frequent releases give people a greater sense of progress than infrequent large ones.

Let your users help make your project more successful.
You need to listen to their needs when designing future versions of your product. In fact, your users should be part of your project's design team.

==== Encourage Outside Developers

When you first open your source code to the outside world, the initial reaction of outside developers is usually very positive.
You can expect comments such as "Wow! You really meant it! There's a lot here!"
After a few weeks, the warts will start to show as developers realize how much work will be required to add the features they want, to improve performance, or to do whatever they care about. 
You need to expect this change in attitude and react appropriately:
Acknowledge the problems and don't be defensive.

Make sure your developers welcome outside comments and do not respond with flames.
Your team needs to encourage outside contributors.
Some have lots of expertise and need to be treated as peers.
Others may lack experience and need mentoring.
The tone you set when you respond to the first suggestions, bug reports, bug fixes, and outside contributions will determine what role people outside your team will play in your project.
It is much easier to start off right than to try to recover later.

Any developer beginning to work on your project needs help to come up to speed.
New developers at your company can often just walk across the hall to ask one of the original developers.
Outside developers do not have that option.
You need to provide them with a systems overview, internal documentation, and email access to the original developer team.

==== Help Outside Efforts Meet Project Quality Standards

Every open-source project establishes a level of quality that new modules and features need to reach in order to become part of the official release.
For some projects, this may mean just that the new code adds more features than bugs.
However, other projects may require documentation of the new features;
support for internationalization, localization, and accessibility;
user-interface (UI) consistency with the project's look and feel;
usability testing; adherence to coding style guidelines;
or any of various other common requirements for product-quality software.
For volunteers who have developed some cool new functionality and want to contribute it to your project, meeting this full list of requirements can easily involve much more work than they spent writing and debugging the code in the first place.

This creates a potential problem:
You want your project releases to be of high quality, but you do not want to treat outside contributions as second-class code that doesn't make it into the official release.
This situation arises in part because a company-sponsored project usually includes technical writers, graphic artists, UI specialists, and others who work with your company's engineers.
One possible solution is to have these people also share their skills with outside developers.

The NetBeans project did this — graphic design for icons was available on request, the Sun UI team was available to provide advice on the user interface for a contributed module, and the Sun documentation team generally took responsibility for documenting everything in the NetBeans standard distribution.
Other assistance was also available to include the new module in the automatic project build scripts.

This doesn't guarantee that all contributed code will be brought up to product quality.
It is common for open-source projects to have an experimental modules section containing new code in various stages of readiness for adventurous users to play with.
Those modules that the community finds promising are candidates for your team along with the rest of the community to improve further.

==== Make Sure Adequate Resources Are Allocated

An open-source project requires more resources than a conventional proprietary one.
If you skimp on providing for the additional needs, it will slow down, or even cripple, your project.
The rate-limiting factor for your project should be the enthusiasm and effort of your community, not the person maintaining the project's website who is too busy to update it or your internal developers who are so overworked they have no time to integrate outside contributions and bug fixes.
Starting up an open-source project implies a commitment to engage with your community and to support it.

Moreover, feedback you receive from your community provides important information you should use to set priorities.
If all your employees are fully assigned to tasks in order to meet your company's goals, then you will be unable to benefit from what you learn from your community.
You need to be able to reassign developers to work on what will make your project most successful, where success is defined in large part by your users.
If your schedule and plans are inflexible, you will miss one of the major benefits of open source — design help from your community.
You also run the risk of alienating members of your community when they see that you do not listen to their ideas, suggestions, and requests.

Of course, you do have limited resources, so you need to identify when your lack of resources is the bottleneck and see if the community can provide the additional manpower.
For example, what if one of your developers who is in charge of a module has so much work to do that it prevents a prompt reply to bug fixes or modifications submitted by outside developers?
In such a case, one or more other developers need to be allowed to also check in changes to that module.
This may be an outside developer who has submitted changes to the module.
As soon as possible, you should grant qualified outside developers check-in privileges.

However, that same overworked module owner must make time to participate in any community discussions relating to that module.
If that is not possible, then another person who can engage with the community needs to take over ownership of the module.
It is okay to delegate work on the module to others, but leadership regarding the module's development requires active participation.

Good project management can make a difference.
A good project manager makes sure that when the project is being hurt by a lack of adequate resources either more resources from within your company are allocated or the community is solicited to provide the additional help.

==== Governance May Need to Change as Your Community Grows

What works for making decisions when you first launch your project will probably change as your community develops.
Initially only your developers will understand the source code and what is needed to change it;
the community is mostly in the role of users commenting on how well the product meets their needs.
That makes it easy for your developers to be the ones who make all the major decisions, especially because they are the ones doing the bulk of the work.
As time goes by and outside contributors become more involved with the project, they will naturally want more of a say in how the project moves forward.
This will include what features go into it, what bugs should be fixed first, and when and how releases are done.

At this point you have a choice:
You can try to keep total control, minimizing community involvement, or you can encourage the community to take on a larger role.
In the latter case, the open-source project will blossom beyond just your company, even though it will still be the largest contributor.

Governance is how things are decided and by whom.
Every community and every open-source project has some sort of governance because decisions must be made all the time.
Governance does not necessarily imply some sort of hierarchy, voting procedures, or strict process.
People who join open-source projects expect some sort of meritocracy in which good work (merit) is rewarded with more rights and responsibilities.
Most open-source projects have good meritocracies, but not all do.

In a company-sponsored open-source project, people who would otherwise be thought of as good-natured dictators might not always be seen as working toward the best interests of the project and community but might be seen as serving some corporate goals.
In these cases, it's a good idea to think about alternatives to pure meritocracy for governance.

The community will typically ignore early discussions on governance — they will be happy letting you run things.
Most developers and users simply want to do their work;
they don't want to have to think about process and governance.
But at some point, people in your community will start to demand a say and may even complain about how evil your company is to try to run everything. 
t that point, little you do will be seen as good and many messages posted will contain suspicions about your motives.
It's like a rebellion, and you just need to expect it and ride it out.

For most company-sponsored open-source projects, some kind of exception-based governance with an appeals body is the best lightweight mechanism to put in place.
Sometimes you need to put something related to governance in the contract with the web-hosting company.
For example, if an appeals body needs to be able to direct the hosting company to give check-in privileges to someone, that will need to go into the contract between your company and the hosting company — otherwise, your company will retain that power.

When your community starts to request a greater say in how the project is run, it is likely that most of the email will come from just a few people.
Do not think that they are just a few malcontents and that everyone else is basically happy with the status quo.
If you do, you will miss your chance to involve your community more in your project — and you may not get another chance.
It is better to think of the few vocal folks as early adopters, who represent the leading edge of your community's thoughts on governance. Work with them to get more community participation.
If you don't engage with them, then they will almost certainly cut back their efforts;
even worse, you will give the rest of your community the impression that you do not want to work with them — that they are somehow second-class citizens, that they should stay in their place and let you call the shots for the project.
Changing this impression later will be difficult.
It is better to not give it in the first place. Working with your community, you have a chance to make the project a true community effort.

Even after you have made it over this hurdle and your community is actively involved in making important decisions about the project, you should expect this process to continue and governance to adapt as your project continues to develop.
In large part, this will be caused by your project's growing in size, both in terms of the number of people involved and the number of active subprojects.
For example, as the original Apache project added more and more subprojects, it needed to create a Project Management Committee to oversee each project.
Further growth led to the creation of the nonprofit Apache Software Foundation with an elected governing board.
As your project grows in size, your project's organization will also need to change.

==== PROVIDE FOR THE DIFFERING NEEDS OF YOUR COMMUNITY MEMBERS

Everyone in your community is unique.
Their reasons for participating, the length of their involvement, how much they contribute, and how much they know all vary from person to person.
In her book _Community Building on the Web_, Amy Jo Kim describes a five-stage membership life cycle that runs from visitor to novice to regular to leader to elder.
Most people will not progress through all five stages — in fact you should expect the number of visitors to be several orders of magnitude larger than all the other stages combined.
To attract and retain people, you need to understand their differing needs and how to encourage people to become more involved.

===== Guide Your Visitors

A visitor is someone who simply wants to see what your community is about.
Like a tourist, a visitor wants to easily find the interesting places and painlessly get an idea of what's up with the project.

Are visitors to your project's website able to easily find answers to their questions or do they become lost as they try to locate information?
A good website has a section devoted to newcomers.
This Visitors Center should contain the following:

* A project mission statement and road map.
* Answers to frequently asked questions.
* Instructions on how to download the current release.
* Tutorials and getting-started documents.
* Press releases and articles about the project.
* A site map and a way to search the website.
* Policies and guidelines for participating in the project.

Most of the larger open-source projects make it easy for visitors to find this type of information.
Two good examples are Mozillafootnote:[https://www.mozilla.org] and GNOME.footnote:[https://www.gnome.org]

You may want to have a separate area for each different category of visitors.
This might be as minimal as having additional sections in your FAQs, or you might have multiple web pages with specialized documents for each group.
For example the OpenOffice projectfootnote:[https://www.openoffice.org] has localized versions of much of its website for speakers of different languages (for example, Czech, French, German, and Japanese), whereas the GNOME project provides separate web pages for users and for application developers.

Another question you must address is how much visitors can participate.
Can they browse mail archives, subscribe to mailing lists, post to mailing lists, add comments to discussion forums, or edit wiki pages?
Generally, you want to maximize how much information visitors can see on your website and minimize barriers to entry.
However, you also need to worry about possible disruptions of conversations;
furthermore your community members may not want to discuss controversial topics in public.

Although many visitors will be new to your project and may need help navigating your website, others will be quite knowledgeable about your project — they may visit your project's website frequently to see what's new.
Do not assume that all the people who care about your project get their news via the mailing lists;
feature news about your project on the home page and update it frequently.

The definition of visitor is someone without a community identity, so any participation visitors do is done anonymously.
It is not necessary to encourage your visitors to join.
However, you should make clear what the benefits and requirements of membership are.
The main reason people join an online community is to do something that requires membership.
For an open-source project, that something is typically being able to ask questions in order to get help in using the project's code and participating in the discussion of the project's future.

===== Welcome Your Novices

Novices are people who have taken the step to join your project.
They may have registered on your project's website or maybe just subscribed to one of your project's mailing lists.
They are interested in your project, but need to learn the ropes about how your community functions.
They need to learn what they can do as members and how to behave.

When they join, you need to welcome them into your community.
A simple way to do this is by sending a welcoming email message. This note should be from a real person, even if it is sent automatically from the mailing list server. Have either the project's founder or your community manager write this welcoming message. It should confirm the novice's membership and explain how the community works. You shouldn't overload new members with information but rather provide links to what they are likely to need to know as they get started working on your project.

On your website, you should help novices learn who's who in your community.
Include a page listing the major contributors, community leaders, and module owners. If you can include pictures of folks, all the better. Introduce novices to your regulars and leaders at community meetings.

Depending on your project, you may want to have a special mailing list, discussion forum, or even a subproject for newcomers to get their initial questions answered.
This can keep the same basic questions from constantly being posted to your main mailing lists.
It lets novices help each other, which sets a good tone for later.
This is another reason to have good FAQ lists and to regularly link to them in the major mailing lists.

Be sure to encourage a friendly attitude that is tolerant of inappropriate postings by novices on project mailing lists.
Gently let the offenders know how your project does things, without personally attacking them.
Redirect inappropriate messages to the correct mailing list.
Discourage flaming.
This attitude encourages novices to participate and is good for your community of regulars too.

===== Reward Your Regulars

Regulars are the lifeblood of your project;
they are the folks who do the work to make your project a success.
They answer questions on the mailing lists, report bugs and bug fixes, contribute code and new ideas, tell others about your project, and do all the other work necessary for your project to move forward.
Do everything you can to encourage your regulars to participate and to retain their interest in your project.

Because many open-source projects are meritocracies, be sure to recognize people doing good work.
Be sure to add them to the project's list of contributors.
Reward them by granting them CVS commit privileges.
Invite them to be part of the core group.
Encourage them to take responsibility for part of the design or a module of code.

A good way to show appreciation for the work your regulars do is to have a spotlight feature on your website's home page or in your project's newsletter that highlights individuals and their work.
You can also encourage them to give a presentation at a community meeting.
Not only does it reward them directly, but it also can educate your community about new functionality and encourage other regulars and novices by giving them an example of what your community values.

Another way to show that you value your regulars is to use resources from your company to further refine one of their contributions to help bring it up to project-quality standards, as described earlier.
Even having one of your graphic artists create a cool logo for a subproject may be appreciated.
Just be sure they feel you are working with them and not trying to take over from them.

The ultimate way to retain your best regulars is to hire them!
It is always hard to find top talent and especially to know how they will function in your company's culture.
With open source, you have a way to try out people and determine whether they fit in with your current team.
Even if they do not live near any of your company's offices you already know that they can work productively from wherever they do live (that is, remotely).
For example, Sun Labs is supporting a small open-source project called Electric, a computer-aided design system for electrical circuits.
When one volunteer really distinguished himself by his contributions, Sun hired him — even though he lives in Moscow and the Sun Labs team is in California.

===== Empower Your Leaders

Your leaders are the people who keep your community running.
Some will be outside volunteers and some will be your employees — a successful project will have a healthy mix of both.
Some will have formal leadership roles, such as module owner, but many roles will be more informal.
For an open-source project, leadership is all about having a vision and working with others to make it happen;
it's not about being in charge, making decisions, or giving orders.

The leaders in your community will naturally take on many different roles:

* Welcoming newcomers to the project and answering their questions.
* Answering technical and procedural questions on your project mailing lists.
* Guiding discussions to help them reach a conclusion.
* Selecting high-quality content to highlight on your website or in your newsletter.
* Coordinating activities such as releases, community meetings, or trade-show demos.
* Providing quality checks on contributed code.
* Policing community discussions to keep them civil, and redirecting messages to the correct mailing list.
* Resolving conflicts and helping the community to make decisions.
* Solving complex technical problems.
* Creating compelling visions and directions for the project.

You need to watch your regulars to see which are starting to assume any of these roles and encourage them to do so.
Try to recruit outside volunteers to oversee visible project-related activities such as module owner, release manager, or newsletter editor.
Establish as soon as possible that community members do important things.

Be sure to provide support for new leaders.
It may be as simple as your community manager trading some tips via email on guiding discussions or assigning an experienced module owner to mentor a new one.
You may want to give all new module owners training on the various tools your project uses.
But recognize that volunteers have limited time, so don't push them to act like full-time employees.

You can reward your leaders and make them more visible by giving them a special place to express their ideas and opinions.
This could be a column in the community newsletter or a series of articles on your website — you could encourage them to write weblogs featured on the project's website.
If a leader is not interested in writing, then post an interview instead.

When you have project-related discussions and meetings inside your company, try to invite outside volunteer leaders to participate.
Be sure to keep them informed on any decisions you make.
All of your project's leaders need to be kept in the loop. You do not want to create an us-versus-them attitude.

===== Honor Your Elders

Elders are respected long-time regulars and leaders who are your community's mentors, teachers, and advisors.
They provide role models for newcomers and regulars on how to behave properly.
They may have stepped down from more active roles such as a leader or contributor, but your community can still benefit from their sharing their knowledge.

Some projects take no notice of when major contributors move on;
at most they may add their names to a list of emeritus contributors and also remove them from the list of active developers.
The Apache Software Foundation's projects have a rule that committers who have been inactive for 6 months or more may lose their status as committers.
Although people can regain their committer status by just requesting it on the project's developer mailing list, the fact that they lost it indicates a certain indifference toward formerly valued community members.

Try to identify potential elders and encourage them to continue to participate in some way.
They may not have time to write code, but perhaps they would like to follow various design discussions — they certainly have the knowledge to do so, including knowledge of your project's history and why previous decisions were made the way they were.
If any of your senior developers move on to another project in your company, see whether you can get their new managers to approve their continuing, though perhaps minimal, involvement on your project mailing lists.

One way to show that you value your elders is to have a special mailing list for them where the community can ask their opinions on important matters that come up.
You can also try to solicit their advice on the regular project mailing lists.
Include them in activities at your community meetings and interview them on your website or in your newsletter.

==== Communication Creates Community

Everyone involved with your project — users, designers, developers, and evangelists — should know what is happening with it.
Everyone needs to know what's new and be able to participate in discussions about various project issues, plans, and designs.
As is mentioned in the section <<let-everyone-know>> in Chapter 6, it is crucial that your internal developers use public mailing lists for their discussions so that the entire community can participate.

Your project should start off with as few mailing lists as possible in order to focus things (see the section <<types-and-number-of-mailing-lists>> in Chapter 6).
This might be one moderated list for infrequent project announcements, one unmoderated list for all user-related questions and comments (including design suggestions), and one unmoderated list for all general developer-related messages (mostly implementation issues).

Your team needs to set a friendly tone on these lists to encourage others to participate (see the section <<posting-etiquette>> in Chapter 6).
You should encourage people from outside of your company to respond to questions from other users/developers.
We recommend the Jini team's policy of waiting 2 days before answering a general user question.
Questions that can be answered by only the core team should be answered immediately.
This should result in a mailing list where users naturally answer most of the posted questions, and the core developers answer only the more difficult, technical ones.

Mailing lists are great for discussions, but not everyone has the time to follow them.
To keep people informed on current issues, you should start a project newsletter.
This newsletter should be published on a regular schedule, ranging from weekly to monthly depending on how active your project is.
The contents of the newsletter should be featured on your project's website.
An example newsletter topic might be a "contributor spotlight" that focuses on some individual who is doing interesting work on the project.
The NetBeans project publishes both a brief weekly newsletter, consisting mostly of links to interesting discussions on its mailing lists, and a monthly newsletter with full articles covering such things as project-related news, feature stories on developers and projects, and pointers to press articles about NetBeans.

===== Community Meetings

To create a real community for your project requires that people get to know one another.
Some of this can happen over mailing lists, but far better are face-to-face meetings.
Have a community meeting as soon as possible and at regular intervals afterward. For smaller projects, you might need to hold your community meeting as part of some larger event, for example as a birds-of-a-feather (BoF) session at conferences such as JavaOne or LinuxWorld.
Try to hold meetings in different locations so more of your community can attend.

A community meeting is a great way to raise the overall level of excitement about your project.
Avoid dull status-reporting sessions. Plan for more interactive formats to take advantage of people being together.
Users and developers usually have lots of questions they would like to ask the core developers, so be sure they get a chance.
Introduce major contributors so people can associate faces with names.
Your developers should also become known as individuals. Reserve time for people to schedule BoFs during the meeting.
Include time for people to informally chat and network.

Don't be constrained by regular meeting formats.
The Jini project has held several open celebrations that they call Jini Fest! where they show off cool aspects of Jini technology and provide an occasion for Jini developers to socialize and network.
These have been more free-form events held during the annual JavaOne conference where groups are invited to show off their work with Jini — both companies using Jini and various Jini Community projects are invited.
Each group hosts a table in a big room. Add food and drink, plus several hundred Jini enthusiasts, and you have an exciting event.
They even filmed part of the event as part of a webcast about Jini technology featured at JavaOne.

Community meetings are also a great place to hold working group meetings.
Getting the major players into a room can speed up decision-making on open issues.
(Be sure to report back via email to the full community on any decisions made at the meeting.)

Other meeting options include phone conferences and online chat sessions.
You might also consider using a webcast to present status updates or other information to your worldwide community.
The Jini project has done several webcasts.
Although webcasts are not as interactive as a meeting, they are good at helping your community to get to know the people presenting material.
Putting a human face on your main developers and contributors helps to build community.
An open-source project has by definition a distributed work group, and you need to explore ways to facilitate communications among the members.

===== Events

Sometimes you can create a strong sense of community and attract others to your project by sponsoring events, such as a reception at a larger conference.
In many cases, conference organizers are receptive to the idea of a special event or sponsorship at their conference to add texture at low cost to them.
Conference organizers often contract with a hotel or conference center to lease a fixed set of the facilities for the entire duration of the conference, and therefore these facilities might be available at low or no cost to you.

A good example is IBM and Eclipse.
At the ACM Conference on Object-Oriented Programming, Systems, Languages, and Applications (OOPSLA) in both 2002 and 2003, IBM sponsored Eclipse receptions.
In 2003, the reception featured a few short speeches but lots of food and demonstrations.
There were no other conference events that evening, so attendance was high.
The event was held in one of the main conference halls, which cost IBM nothing, and the entire affair cost less than $20,000 for the food and drinks.
It was at this conference and reception that Erich Gamma and Kent Beck's book on contributing to Eclipse went public.

==== New Forms of Communication: Wikis and Weblogs

The tools available for online communication continue to evolve.
As they do, new opportunities arise for people in open-source projects to interact and collaborate with each other.
Two particularly promising new technologies are the wiki and the weblog.

===== The WikiWikiWeb

A wiki is a website that allows people to edit web pages collaboratively.
A wiki makes it easy for anyone to view, edit, and create web pages using just a web browser. A very simple markup scheme allows basic text formatting.
In the original wiki, a link to another wiki page was automatically created by writing several words with their first letters capitalized and with no spaces between them, for example, OpenSource or CollaborativeDevelopment.
If there was not already a page with that name, a new one was created.

A wiki is a great way for a community to create a group document.
As members browse the existing pages, any time they see mistakes or want to make additions all they need to do is press the _Edit this page_ button displayed at the bottom of the page.
This loads the current text of the page into a form in which it can be edited.
The _Save page_ button in the form saves a new version of the page, which is immediately made available for all to see.

The first wiki websitefootnote:[http://c2.com/cgi/wiki] was established by Ward Cunningham in 1995.
Ward originally called it the WikiWikiWeb from the word _wiki wiki_, which means "quick" in the Hawaiian language.
For another example, check out the Wikipedia,footnote:[https://wikipedia.org] where, in only 3 years, the online community has created an open-content encyclopedia of almost 300,000 entries (as of July 2004).
Open-source projects have recently begun to use wikis.
The Apache Software Foundation has a wikifootnote:[http://wiki.apache.org/general] used by its various projects, and the GNOME project has set up a wikifootnote:[http://gnomesupport.org/wiki] to provide support.

Writing in wiki pages consists of either unsigned, deliberately anonymous text that is intended to be community material which others are encouraged to update and improve (for example, a page on the Apache wiki describing how to do log rotation for the James mail/news server) or a series of signed comments where people hold a form of conversation as they try to reach an understanding of the issues involved (for example, a page discussing which Java IDE to use, also on the Apache wiki).
Anyone can both reorganize the conversational threads to clarify the material, possibly moving them to new pages, and revise the community material based on the comments made.
Over time more and more community-owned text is created expressing the community consensus and the concluded discussions may be removed. 
Many wikis provide simple version-control mechanisms so that no text is lost, and archiving important versions of a wiki page can make looking at history easy.

Most wikis have a special _RecentChanges_ page that displays an automatically generated index of all the wiki pages that have been changed recently.
Many people check the _RecentChanges_ page frequently to see what is new on the wiki.

Many people's immediate reaction when they first hear about wiki is that it cannot possibly work.
People worry that someone will come along and delete what is there or write random garbage all over pages.
This indeed can, and does occasionally, happen, but as soon as the wiki's community members notice the problem, one of them erases the graffiti and restores the page's original contents from the previous archived version.
After continually having their "work" removed, the offending individuals usually quickly give up and go elsewhere.

A more common problem is that no community consensus emerges, possibly because the community is split into opposing viewpoints on some issue.
Then it is important that the community try to express each of the viewpoints rather than resolving the issue to a single "correct" one. 
This requires a real sense of community and a respect for the beliefs of other community members.
The Wikipedia calls this writing with a neutral point of view and has a good description of how to do this.footnote:[http://en.wikipedia.org/wiki/Neutral_point_of_view]

Another reason that discussions sometimes do not resolve is that the community is exploring a new area and just doesn't know enough yet. 
In this case, the discussions remain visible as a reminder that the issue is still open.
As individuals and hence the community learn more, people may eventually add to the discussion and reorganize it.

The wide-open nature of the wiki and most people's unfamiliarity with wikis can present a barrier.
People can be afraid of what will happen to what they write or unsure what type of contributions are acceptable.
The tone set by the community will either encourage new folks to join in or discourage them from doing so.
Once people contribute and begin to edit wiki pages, they gain a feeling of empowerment and often develop a vested interest in overseeing the wiki as a whole.

A wiki is a community effort and each develops its own culture.
In general, the sense of working together to build a better understanding seems to encourage people to be more polite than many other Internet activities do — perhaps because on a wiki any flames, spam, and trivia can be easily deleted, while the constructive comments typically expand and grow.

Coming to a common place, sharing a vocabulary, and working together over time on common goals all help to make the people using a wiki into an actual community.

For more information on wikis, see the book _The Wiki Way: Collaboration and Sharing on the Internet_ by Bo Leuf and Ward Cunningham.

===== Weblogs or Blogs

A weblog (also known by its contraction, "blog") is an online journal with entries on whatever topic or topics interest the author, usually including links to online articles, news, or other blogs.
Blogs enable people without much web experience to create, format, and post diarylike entries with ease.
Blogs are a great way for an individual to have a place to express opinions.

We have discussed mostly communities built up by collaboration, but the blog focuses on the individual.
Helping to create a strong individual identity also helps to build community — community is about getting to know the individual members in the community better over time, something that blogs help to do.
They also help to bridge the gaps among multiple communities that the blogger is a member of. 
any people who write blogs include a list of links to other blogs that they read.
This _blogroll_ helps to define the blogging community that a person identifies with.

A good way for an open-source project to make use of blogs is to have a news page that displays the latest blog entries from selected community members or a project group blog.
Most blogs provide an RSS (_Rich Site Summary_ or _Really Simple Syndication_) feed that other web pages can subscribe to.
Using this RSS feed, a project can feature on its home page headlines for the most recent relevant blog entries.

Having key people in your project write a blog (called "blogging") is another channel for getting important information to your community;
it is also a good way to reach people outside of your community who are interested in your project.
Anyone can subscribe to the RSS feeds from your blogs and thus get timely updated news concerning your project.

A good book on how to write a blog is _The Weblog Handbook: Practical Advice on Creating and Maintaining Your Blog_ by Rebecca Blood.

=== Community Outreach

Your project does not exist in a vacuum.
Strengthen your connections with other open-source projects. Do this to be a good citizen and because it will benefit your project.
If your software engineers establish good reputations with the open-source community it will benefit your company.

Being active in the larger world of open source will help you with your open-source project.
Your project infrastructure undoubtedly will use many open-source tools such as CVS, Bugzilla, and Perl, so you may want to become involved in the debates about their future development.
Seeing how other projects are run will give you ideas about what your project should or should not do.

Market your project to other open-source efforts.
These provide a natural audience for the software you develop and are a source of potential contributors.
For example, if you create an application that runs on Linux, then you should work with groups creating Linux distributions so that your application will be included — OpenOffice is part of the Linux distributions from RedHat, SuSE, and Mandrake.

==== Establishing Credibility with the Open-Source Crowd

Beyond the day-to-day activities of your project, there are some other things you can do to establish better credibility with the larger open-source community.
The bigger and more visible your project is, the more important it is for people working on other open-source projects to see you as being part of this larger open-source community.

First, it will help if you are using a license that has been blessed by the more well-known spokespeople for open source, such as Richard Stallman, Tim O'Reilly, Bruce Perens, and Eric Raymond.
If your project uses an OSI-certified open-source license such as BSD, Mozilla, or the GNU GPL, then these spokespeople will be able to go on record as saying your project is true open source and a Good Thing.
If your project is using a proprietary or shared source license, they and the press will be sure to point out that your project is not open source.
This issue arose with Sun's Jini project, which uses the Sun Community Source License (SCSL) — even though Sun was quite clear in stating that it was creating a gated community and not trying to do true open source, the press and some open-source pundits kept saying, "Yes, but it's not open source."
This deflected attention from the Jini technology and slowed down the growth of the project around it.

Second, you should establish strong, positive connections with other open-source projects.
If your project uses tools or modules developed by other open-source projects or your project produces tools or modules that other open-source projects could benefit from, then not only should you be involved with these other projects, but you should try to entwine their projects and yours as much as possible.
An ideal situation is for your project to be part of the planning process — for future features and the timing of releases — for those other projects.
The OpenOffice project started with the intent to integrate its office productivity suite with the GNOME desktop, so it became involved in the GNOME community, contributing code and bug fixes back to the GNOME project.
As the collaboration deepened, technologies and components from each project became part of the other, so that OpenOffice can be said to be deeply embedded into GNOME.
The more your project is seen as not only supporting but deeply integrated with other open-source efforts, the more your project — and thus your company — will be considered a good member of the larger open-source community.

You should also establish dialogs with open-source developers not involved with your project.
Have your internal developers both read and post to places such as Slashdot.footnote:[https://slashdot.org]
Encourage them to start individual weblogs.
The more individuals from your company that people see participating in open-source forums — especially when their email addresses include your company's domain name — the harder it will be for them to see your company as a large faceless corporation.
It is fine for your company's developers to express whatever views they have, but they should strive for some restraint and avoid too much flaming.
As mentioned in the section on <<posting-etiquette>> (Chapter 6), they need to remember that even though they are posting as individuals, people will read their notes as being your company's official policy.
When your company's actions are attacked, they should wait a bit to first give outside people a chance to defend your company — statements from people not employed by your company are more effective than statements from employees.
Of course, if the criticism is valid, your developers should immediately acknowledge it and fix things.

=== Harvesting Innovation

If you're trying to do innovation based on your open-source project, then you need to do more than just successfully run the project — you need to harvest what we have called triggers.
Harvesting from your community doesn't involve any sort of thievery or unethical behavior — it means simply finding out what your community members are doing;
what problems they're having;
what books, trends, and technologies they are engaged in; what conferences they attend;
and how they are using your open-source software.

Your community manager can lead the way by being sociable and getting to know the active members of the community.
Your developers can also get to know community members.
Without being intrusive, you can easily come to find out what kinds of uses your community members are making of your open-source software.
Are there problems that seem beyond the scope of the open-source project itself?
Are there related problems that could be addressed with other products or add-ons?
Are people using your technology clustering in application areas you didn't anticipate?
Are they talking about a new technology or reading a new book?
Are they working on some particular other open-source projects? Are they upgrading their hardware in a pattern?

When you hold your community meetings, try to arrange for community members to talk about how they are using the project's technology.
Use these opportunities to learn about the people who have come to your technology on their own.
And learn about what they are doing with it.

Get your developers together periodically to share what's been learned and brainstorm new opportunities.
Have a variety of people in your company look at the community.
When you think you have something, it might turn out that some community members your community manager is friendly with are willing to discuss your ideas.

The key is just to keep your eyes open — don't pry and don't do official-looking surveys.
Simply be aware of what your community is up to, who is in it, and what they share voluntarily about what they are doing and the problems they're having.

=== Welcome the Unexpected

One of the strengths of open source is that contributors always surprise you.
When someone submits a new module that takes things in a new direction, be willing to devote some resources to making it a bigger success.
If some people start using your product in ways you didn't expect, check it out and see whether there's a whole new market waiting for you.
Most of all, listen to what your community tells you it wants and needs.
You have made an investment of company resources in order to use open source, so be sure to get the greatest possible return on that investment by harvesting the innovation that your community creates.
