name: Build book

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2
        with:
          persist-credentials: false
      - name: Install toolchain
        run: sudo apt-get install -y asciidoctor ruby-asciidoctor-pdf pandoc
      - name: Build book
        run: make all
      - name: Upload output
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # tag=v4.4.3
        with:
          name: IHE-${{ github.sha }}.pdf
          path: output/

  release:
    runs-on: ubuntu-latest
    needs: build-book
    steps:
      - name: Download files
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # tag=v4.1.8
      - name: DEBUG print ref
        run: echo ${{ github.ref }}
      - name: Create release
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # tag=v2.1.0
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            IHE.pdf
            IHE.zip
